### ISSUE TITLE
Empty genmap outputs

### ISSUE THREAD

**Issue by ryantwaz** [pothiers/vvote#6]
Just tried:  genmap -v MockSOVC.xlsx FinalLVR.xlsx mockraces mockchoices
The program appears to run but output files are empty.  Input files look OK to me.

**Comment by pothiers** [comment]
either provide me with your inputs or use ones from https://github.com/pothiers/vvote/tree/master/tests/data
Are you sure your output files are completely empty ("wc -l mock* returns zero lines for both.  Or is there a header line?  If you are using a files where all strings match, there will be no mapping strings.

**Comment by ryantwaz** [comment]
Ah, I assumed there would be entries even if all strings matched.  That must be it. I’ll try it on the real election data.

**Comment by pothiers** [comment]
Now write all SOVC races in map so at least that one will be "full"
